export const types = Object.freeze({
  // Sync
  FILMS_FILL: 'FILMS_FILL',
  FILMS_START_FETCHING: 'FILMS_START_FETCHING',
  FILMS_STOP_FETCHING: 'FILMS_STOP_FETCHING',
  FILMS_SET_FETCHING_ERROR: 'FILMS_SET_FETCHING_ERROR',
  // Async
  FILMS_FETCH_ASYNC: 'FILMS_FETCH_ASYNC',

  // Sync
  FILM_FILL: 'FILM_FILL',
  // Async
  FILM_FETCH_ASYNC: 'FILM_FETCH_ASYNC'
});