export const types = Object.freeze({
  // Sync
  PEOPLE_FILL: 'PEOPLE_FILL',
  PEOPLE_START_FETCHING: 'PEOPLE_START_FETCHING',
  PEOPLE_STOP_FETCHING: 'PEOPLE_STOP_FETCHING',
  PEOPLE_SET_FETCHING_ERROR: 'PEOPLE_SET_FETCHING_ERROR',
  // Async
  PEOPLE_FETCH_ASYNC: 'PEOPLE_FETCH_ASYNC',

  // Sync
  PERSON_FILL: 'PERSON_FILL',
  // Async
  PERSON_FETCH_ASYNC: 'PERSON_FETCH_ASYNC'
});